<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>flex-dax-tx</AssemblyName>
    <RootNamespace>M0LTE.Flex.Tools.DaxTx</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/M0LTE.Flex/M0LTE.Flex.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="M0LTE.Flex.Tools.Tests" />
  </ItemGroup>

</Project>
